proyecto_proyecto_homepage:
    path:     /hello/{name}
    defaults: { _controller: ProyectoProyectoBundle:Default:index }

proyecto_habitacion:
    resource: "@ProyectoProyectoBundle/Controller/"
    type:     annotation
    prefix:   /
