<?php

namespace Proyecto\ProyectoBundle\Entity;

/**
 * Configurables_preciosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Configurables_preciosRepository extends \Doctrine\ORM\EntityRepository
{
}
