<?php

namespace Proyecto\ProyectoBundle\Entity;

/**
 * Config_bebidasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Config_bebidasRepository extends \Doctrine\ORM\EntityRepository
{
}
