<?php

namespace Proyecto\ProyectoBundle\Entity;

/**
 * HabitacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HabitacionRepository extends \Doctrine\ORM\EntityRepository
{
}
