<?php

namespace Proyecto\ProyectoBundle\Entity;

/**
 * PideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PideRepository extends \Doctrine\ORM\EntityRepository
{
}
