Proyecto\ProyectoBundle\Entity\bebidas:
    type: entity
    table: null
    repositoryClass: Proyecto\ProyectoBundle\Entity\bebidasRepository
    id:
        numero:
            type: integer
            id: true
    fields:
        cerveza:
            type: integer
        vino:
            type: integer
        agua:
            type: integer
        refrescos:
            type: integer
        alcoholicas:
            type: integer
    lifecycleCallbacks: {  }
