Proyecto\ProyectoBundle\Entity\Configurables_precios:
    type: entity
    table: null
    repositoryClass: Proyecto\ProyectoBundle\Entity\Configurables_preciosRepository
    id:
        nombre:
            type: string
            length: '40'
            id: true
    fields:
        valor:
            type: float
        tipo:
            type: string
            length: '30'
    lifecycleCallbacks: {  }
