Proyecto\ProyectoBundle\Entity\Habitacion:
    type: entity
    table: null
    repositoryClass: Proyecto\ProyectoBundle\Entity\HabitacionRepository
    id:
        numero:
            type: integer
            id: true
    fields:
        contNac:
            type: integer
            column: cont_nac
        contInter:
            type: integer
            column: cont_inter
        tipo:
            type: string
            length: '10'
        categoria:
            type: string
            length: '8'
        camaInd:
            type: string
            length: '2'
    lifecycleCallbacks: {  }
