Proyecto\ProyectoBundle\Entity\Pide:
    type: entity
    table: null
    repositoryClass: Proyecto\ProyectoBundle\Entity\PideRepository
    id:
        codigo:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        fInicio:
            type: date
            column: F_inicio
        fFin:
            type: date
            column: F_fin
        tipo:
            type: string
            length: '8'
    lifecycleCallbacks: {  }
