Proyecto\PBundle\Entity\Persona:
    type: entity
    table: null
    repositoryClass: Proyecto\PBundle\Entity\PersonaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: '30'
        cedula:
            type: string
            length: 8
        direccion:
            type: string
            length: 255
    lifecycleCallbacks: {  }
